# This workflow will perform the following steps for pushes the the develop branch
# * build the Schema and the Guidelines with Ant
# * publish the Schema to music-encoding/schema under ./dev
# * publish the Guidelines to music-encoding/guidelines under ./dev

name: Deploy Schema and Guidelines

on:
  workflow_dispatch: # trigger manually
    inputs:
      fork:
        description: "music-encoding fork to use"
        required: true
        default: "music-encoding"
      branch:
        description: "Branch to use"
        required: true
        default: "pdf-guidelines"

env:
  # schema
  SCHEMA_REPO: ${{ github.repository_owner }}/schema
  SCHEMA_BRANCH: main

  # test
  BUILD_REPO : ""
  BUILD_BRANCH: ""
  BUILD_DIR: test-dir
  BUILD_VERSION: v5.0.0-dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      ### BUIDLING THE SCHEMA AND THE GUIDELINES ###
      - name: Checkout main repo
        uses: actions/checkout@v3
        
      - name: Get inputs
        run: |
          fork=${{ github.event.inputs.fork }}
          branch=${{ github.event.inputs.branch }}
          
          echo BUILD_REPO=$fork/music-encoding >> $GITHUB_ENV
          echo BUILD_BRANCH=$branch >> $GITHUB_ENV

      - name: Checkout BUILD_REPO into BUILD_DIR
        uses: actions/checkout@v3
        with:
          # repository to check out
          repository: ${{ env.BUILD_REPO }}
          # ref (branch, tag or SHA) to check out
          ref: ${{ env.BUILD_BRANCH }}
          # relative path under $GITHUB_WORKSPACE to place the repository
          path: ${{ env.BUILD_DIR }}
          # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
          # recursively checkout submodules.
          submodules: recursive

      - name: Verify
        run: | 
          cd ${{ env.BUILD_DIR }}
          pwd
          ls -R

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Get XML Info
        id: getxml
        uses: mavrosxristoforos/get-xml-info@1.1.0
        with:
          xml-file: '${{ env.BUILD_DIR }}/source/modules/MEI.shared.xml'
          xpath: "//*[local-name() = 'classSpec'][@ident = 'att.meiVersion']//*[local-name() = 'defaultVal']"

      - name: Verify version
        run: |
          echo ${{ steps.getxml.outputs.info }}

      - name: Build with Ant
        # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          ant -noinput -buildfile build.xml init
          ant -noinput -buildfile build.xml -lib lib/saxon/saxon-he-10.5.jar -Dgithub.sha=${{ github.sha }} -Dversion=${{ steps.getxml.outputs.info }}

      - name: Verify
        run: | 
          cd ${{ env.BUILD_DIR }}/build/assets/images/
          pwd
          ls -R

      - name: Render live MEI image samples to SVG
        # For more information see: https://github.com/Edirom/staticVerovioConverter
        # MEI files are taken from and SVGs are placed into folder: /source/examples/verovio
        working-directory: ${{ env.BUILD_DIR }}/build/assets/images/
        run: |
          docker run --rm -v $(pwd):/data edirom/staticverovioconverter:latest
   
      - name: Verify
        run: |
          cd ${{ env.BUILD_DIR }}/build/assets/images/
          pwd
          ls -R
   
      - name: Verify
        run: |
          cd ${{ env.BUILD_DIR }}/build/
          pwd
          ls -R

      - name: Generate complete PDF with PrinceXML 
        # For more information see: https://www.princexml.com/
        working-directory: ${{ env.BUILD_DIR }}/
        run: docker run --rm -v $(pwd):/out yeslogic/prince:14.2 /out/build/MEI_Guidelines_${{ env.BUILD_VERSION }}.html --log /out/build/princeLog.txt -v
        
      - name: Verify build directory
        run: |
          cd ${{ env.BUILD_DIR }}/build/
          pwd
          ls -R
        
      - name: Verify dist directory
        run: |
          cd ${{ env.BUILD_DIR }}/dist/
          pwd
          ls -R
        
        
      # Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          path: | 
            ${{ env.BUILD_DIR }}/dist
            ${{ env.BUILD_DIR }}/build/*.pdf
            ${{ env.BUILD_DIR }}/build/*.html
            
